### ISSUE TITLE
Include surface temperature statistics from verification data in prognostic run report

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#1158]
Currently surface temperature statistics are not computed in the prognostic run report for verification data.  I think this is related to the name used for the surface temperature diagnostic in SHiELD output (it is called `tsfc_coarse` instead of `TMPsfc_coarse`).  See e.g. gs://vcm-ml-raw/2020-05-27-40-day-X-SHiELD-simulation-C384-diagnostics/gfsphysics_15min_coarse.zarr/tsfc_coarse

Is there a mechanism to handle diagnostic names that differ between prognostic run outputs and verification outputs or is this just something that we should correct in prognostic (or verification) runs going forward?

**Comment by nbren12** [comment]
> Is there a mechanism to handle diagnostic names that differ between prognostic run outputs and verification outputs or is this just something that we should correct in prognostic (or verification) runs going forward?

Manually renaming the field seems appropriate. I would try to keep the names consistent between SHiELD runs to ease comparing Pyre and nudged C3072 runs.

**Comment by nbren12** [comment]
In my microphysics tuning experiments, I tried wrapping Datasets with a class that enforced a consistent set of names: https://github.com/VulcanClimateModeling/explore/blob/9c70ad88d882a7105112e18932ead56e17a69550/noahb/microphysics-tuning/models.py#L89. What do you think about that approach?

**Comment by oliverwm1** [comment]
> Is there a mechanism to handle diagnostic names that differ between prognostic run outputs and verification outputs or is this just something that we should correct in prognostic (or verification) runs going forward?

The only renaming in place is for dimensions (switch to `x`, `y`, etc) and removing of `_coarse` suffix if it exists. We could introduce some kind of mechanism, but enforcing consistent names in our runs does help make sure we're looking at the same thing I think.

**Comment by spencerkclark** [comment]
This is fine -- if there is not something already in place it is likely easier to just harmonize these things in the conversion of SHiELD outputs to zarr.  That of course doesn't help the current situation for surface temperature.  For that we could create a copy of the `tsfc_coarse` variable with the name `TMPsfc_coarse` in the same dataset (this would allow old scripts to continue using the old variable).

**Comment by oliverwm1** [comment]
Yeah that would work. If you can't or don't want to modify the currently existing dataset, you could also add a new one that just includes this variable and add it to the catalog. During the data loading, multiple datasets of verification data can be merged to form a single "physics" or "dycore" dataset: https://github.com/VulcanClimateModeling/fv3net/blob/54c181c868dc07b417c15f6a81a9117219c6622d/workflows/prognostic_run_diags/fv3net/diagnostics/prognostic_run/config.py#L5

**Comment by oliverwm1** [comment]
I think another inconsistency between the SHiELD data and ours is the naming of lowest layer temperature. `TB` in SHiELD and `TMPlowest` in our runs IIRC.

**Comment by nbren12** [comment]
I think we are bound to have inconsistencies and need some kind of bespoke logic for the SHiELD runs since those are done so infrequently relative to our code/diagnostic changes for prognostic runs. I therefore think it makes the most sense to leave the SHiELD runs naming conventions the same as the ones in the diag_table and keep them as consistent as possible from run to run. The following checks are required to really trace what a given variable is coming from in the prog run report
1. Figure out the variable the label corresponds to in the plotting func,
2. Figure out any name transformations in the loading functions
3. Look at your diag table from the ShiELD run for the mapping from output name to in-source name
4. browse ShiELD source code

Renaming things in post processing to zarr would only make this lookup chain longer, by introducing a step between 2 and 3. @spencerkclark also does not typically share this post processing code with the team since it is GFDL IP as far as I know, so the less it does the better IMO.

**Comment by nbren12** [comment]
That said, we can improve the names in the `diag_table` of feature SHiELD runs.

**Comment by mcgibbon** [comment]
@spencerkclark can we close this issue, or is it still relevant? Is it going to be fixed?

**Comment by oliverwm1** [comment]
Actually this was just resolved by #1814 (at least for the 40-day SHiELD verification_)

**Comment by spencerkclark** [comment]
I see, so there's kind of a solution for general renaming in there.  I guess to fully address this issue, we'll have to populate the `VERIFICATION_RENAME_MAP` dictionary for the PIRE run too.

**Comment by mcgibbon** [comment]
Closed by #1830
