### ISSUE TITLE
Move halo code to vcm

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1482]
I noticed that @mcgibbon added some cool and useful halo code to fv3fit: https://github.com/ai2cm/fv3net/blob/8cd81163d3092f3b699b40e7f37a9db46649285e/external/fv3fit/fv3fit/keras/_models/shared/halos.py#L130

This actually seems pretty general purpose, so it would be nice to move to the `vcm.cubedsphere` namespace which already has a lot of xarray routines for dealing with cubed-sphere data (e.g. coarsening, to_cross, wind rotation, etc). The current code seems to fit that location better than its current home `fv3fit.keras._models.shared`: it doesn't depend on tensorflow.

To be concrete, can we make the following public API?
```
vcm.cubedsphere.append_halos
```

**Comment by mcgibbon** [comment]
I agree, it's more general purpose than its current placement suggests.

I was actually thinking this should be moved to fv3gfs-util (or I suppose pace-util) once the dust has settled a bit on the use/implementation of the feature. It's more generally useable outside of our group, while vcm is harder to install due to its heavier dependencies and isn't presented as an outside tool past use in our workflows. Is it OK to plan that in December I will move this to fv3gfs-util?

**Comment by nbren12** [comment]
This was just a suggestion that I found the location of this code in our
repo a bit out of place given that it is most similar and datastructure and
usage to the routines in `vcm.cubedsphere`.  Does fv3gfs.util even depend
on xarray at the moment? I thought Quantity was the main data structure
used there?

What can we do to make you feel more comfortable contributing to vcm? I
realize you often run into issues with the `mappm` component...worried
about coupling developing between fv3net and the pace repo. None of us
other than you contribute there.

>

**Comment by mcgibbon** [comment]
Xarray is currently a requirement for interacting with netcdf data. This feels like a very natural optional requirement, since you will never be calling a function that takes in an xarray dataset without having xarray installed.

> worried about coupling developing between fv3net and the pace repo. None of us other than you contribute there.

I think it's important we decide on a healthy way to contribute to pace. @frodre has been working with @elynnwu contributing to that repo. As the frontend parts of the model are created and become stable/useable, I see the Pace model itself being a much better environment than the wrapper for modifying the physics. A priority for me as a DSL member is to make sure the model satisfies our research needs on the ML team.

**Comment by mcgibbon** [comment]
YAGNI, hasn't come up since November. May re-open if we find a use case for this code outside of fv3fit.
