### ISSUE TITLE
skill regression in control simulation

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1724]
@frodre it looks like the control configuration on master is not training particularly well: https://wandb.ai/ai2cm/microphysics-emulation/runs/2iie3ej1?workspace=user-nbrenowitz

This is an example of good skill: https://wandb.ai/ai2cm/microphysics-emulation/runs/1h6ancbo?workspace=user-nbrenowitz

If I had to guess, we lost skill from changing the shuffle buffer size and using a smaller train_set to fit the temperature scales.

**Comment by nbren12** [comment]
It's possible this is a one-off error. It doesn't look like the other experiments have it.

**Comment by frodre** [comment]
Agree this looks like a transient error.  For future reference, I found a coarse master commit range where the training regression seemed to be present.  I tested it in the docker images associated with the master commit using a basic RNN config with the adjustment adding the final fields to the loss function instead of just the T-scaled difference loss.  The tell was a loss value >20 after the first epoch, usually associated with the humidity differences.  When the RNN was training as expected the loss was < 10.

```
 python3 -m fv3fit.train_microphysics --config-path precpd_limit/rnn-control.yaml --use_wandb false --epochs 3 --nfiles 50 --valid_freq 10 --checkpoint_model false
```

| Training Status | Date | SHA | Image |
|--------------|------|------|------|
| working | Mon Mar 28 | c15d8747 | fv3fit |
| broken | Thu Mar 24 | 79ebe213dbdc18886af043220a609d2f3c847dac | fv3fit |
| broken | Tue Mar 22 | d6a0ed27eb58dae25782e9c6613774562f2e64f0 | prognostic_run_gpu |
| working | Tue Mar 8 | 04de1e27915f3af51cafec4434c7041425257c9e | prognostic_run_gpu |

**Comment by nbren12** [comment]
Possibly related to #1745. The fv3fit image had different deps than everything else.

**Comment by nbren12** [comment]
I think we've moved past this issue and have a new "control".
