### ISSUE TITLE
prognostic run cache misses after recent PR

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#2061]
# Problem 

A common workflow is to make some changes locally, and then rebuild the prognostic run image and push. I frequently use this for experiment branches. Once the image was initially built, fv3net source modifications would take maybe 30 seconds to rebuild and push the docker image to GCR.  After 61c6fe057d69ddfa73feae57648d606aac561735 it takes about 10 minutes.

# Discussion

61c6fe057d69ddfa73feae57648d606aac561735 significantly slowed this worfklow since now all the dependencies are installed after the fv3net packages are copied in. 

To improving caching I suggest the following order of operations in the dockerfile

1. build FV3
2. install python deps
3. install fv3gfs-wrapper
4. Copy in fv3net code and install

# Implementation

The solution we previously had was to install all the deps before the fv3net code. The list of needed deps is generated here: https://github.com/ai2cm/fv3net/blob/8683d182410dd99ecd216c764718ddc6e338ca70/Makefile#L250. This makefile target has a similar role to `install_fv3net_python_dependencies.sh`. To reuse code, I would modify `install_fv3net_python_dependencies.sh` to instead generate a requirements.txt. You can use it in the makefile target listed above...it will run on the host rather than in the dockerfile. Then you should be able to restore the better caching order of operations above.

cc @spencerkclark @oliverwm1

**Comment by spencerkclark** [comment]
Indeed, I realized this while working on #2047.  `install_fv3net_python_dependencies.sh` uses the `requirements.txt` file generated by that makefile rule as an input.  I agree we should split that script into two (one that installs the packages specified in the `requirements.txt` file and one that installs the fv3net packages) such that those steps can be called on either side of installing the wrapper.

Apologies for breaking this in #2035.  Through working on #2047 I feel like I've developed a better understanding of the way the caching works and a better appreciation for why things were set up the way they were before (particularly that installing the fv3net packages came last because those are the things we change most frequently, and are also very quick to install compared to all of the non-local dependencies from the `requirements.txt` file).
